server:
  port: 8088


spring:
  mvc:
    view:
      prefix: /
      suffix: .html

  datasource:
    dynamic:
      primary: lotteryERP
      strict: false
      datasource:
        lotteryERP:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
          url: jdbc:mysql://127.0.0.1:3306/lottery_security?characterEncoding=utf-8&serverTimezone=UTC
        lottery:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: root
          url: jdbc:mysql://127.0.0.1:3306/lottery?characterEncoding=utf-8&serverTimezone=UTC







#    url: jdbc:mysql://127.0.0.1:3306/lottery_user_login?useSSL=false&serverTimezone=UTC



  redis:
    port: 6379
    host: 127.0.0.1



mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  type-aliases-package: com.banana69.*.entity
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.banana69.lotteryERP.interfaces.lottery.dto, com.banana69.lotteryERP.interfaces.sys.entity

dubbo:
  application:
    name: Lottery-ERP
    version: 1.0.0
  registry:
    #    address: N/A
    #    address: #multicast://224.5.6.7:1234
    address: zookeeper://127.0.0.1:2181
#    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1


